name: padiff

channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge

dependencies:
  - python=3.10
  - pip>=23
  - pytorch=2.4.*
  - pytorch-cuda=12.1
  - pyg=2.5.*
  - openbabel=3.1.*
  - pdb2pqr>=3.6
  - pip:
      - -r requirements.txt
      - git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3
